name: flutter_application_mengabsen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.3.0
  geolocator: ^10.0.0

  # PDF Downloader & File Opening
  url_launcher: ^6.2.5
  path_provider: ^2.1.4
  open_file: ^3.3.2

  # File & Network
  file_picker: ^8.1.3
  path: ^1.8.3
  http: ^1.2.2     # ðŸ’¥ INI SUDAH DIPERBAIKI

  # Media Picker
  image_picker: ^1.1.2

  # UI Library
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo_iota.png
    - assets/meating.png
    - assets/logo_kecil.png
    - assets/Mengabsen.png
    - assets/Powerby.png
    - assets/Ilustrasi.png
    - assets/banner.png
    - assets/banner1.png
    - assets/banner2.png
    - assets/banner3.png
    - assets/vector.png
    - assets/default.png
